using System;
using System.Collections.Generic;
using System.Text;
using Newtonsoft.Json;

///
/// Auto generated by https://jsonformatter.org/json-to-csharp
/// 

namespace SyncTool.Core.Models.CC;
public partial class CampaignList
{
    [JsonProperty("_links")]
    public Links Links
    {
        get; set;
    }

    [JsonProperty("campaigns")]
    public Campaign[] Campaigns
    {
        get; set;
    }
}
